config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  resources :todos
  root "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :todo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @title = "Home"
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[index show]
  before_action :correct_user, only: %i[edit update destroy]
  # GET /todos or /todos.json
  def index
    @todos = Todo.all
    @title = 'Todos'
  end

  # GET /todos/1 or /todos/1.json
  def show
    @title = @todo.title
  end

  # GET /todos/new
  def new
    #@todo = Todo.new
    @todo = current_user.todo.build
    @title = 'New Todo'
  end

  # GET /todos/1/edit
  def edit
    @title = @todo.title
  end

  # POST /todos or /todos.json
  def create
    #@todo = Todo.new(todo_params)
    @todo = current_user.todo.build(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @todo = current_user.todo.find_by(id: params[:id])
    redirect_to todos_path, notice: "Not authorized to edit this todo" if @todo.nil?
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:user_id, :title, :content, :due, :done)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_nav.html.erb
<nav class=" purple">
    <div class="nav-wrapper">   
      <%= link_to "RailScript", root_path, class: 'brand-logo' %>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><%= link_to "To_do list", todos_path %> </li>
        <% if user_signed_in? %>
          <!-- Dropdown Trigger -->
          <li> <a class='dropdown-trigger ' data-target='dropdown1'><%= current_user.email %></a></li> 
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %> </li>
        <% end %> 
      </ul>
    </div>
  </nav>
  <!-- Dropdown Structure -->
  <ul id='dropdown1' class='dropdown-content'>
    <li class="disabled"><a class="disabled black-text" href="#!">Acount Management</a></li>
    <li class="divider" tabindex="-1"></li>
    <li><%= link_to "Edit perfil", edit_user_registration_path %> </li>
    <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li>
  </ul>
  <ul class="sidenav" id="mobile-demo">
    <li><a href="sass.html">Sass</a></li>
    <li><a href="badges.html">Components</a></li>
    <li><a href="collapsible.html">Javascript</a></li>
    <li><a href="mobile.html">Mobile</a></li>
  </ul>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %>
     <%= csp_meta_tag %> 
     <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %> 
     <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <%=stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track':'reload' %> 
    <%= javascript_pack_tag 'application', 'materialize', 'app','data-turbolinks-track': 'reload' %>
   
  </head>

  <body>
      <header>
        <%= render 'layouts/nav'%>
      </header>
      <main>
        <%= yield%>
      </main>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation  red lighten-4">
      <p class="red lighten-1"><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</p>

      <ul>
        <% todo.errors.each do |error| %>
          <li class=" red-text lighten-1"><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.number_field :user_id, id: :todo_user_id, class: 'validate', value: current_user.id, type: :hidden %>
  <div class="row">
    <div class="input-field col s12">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'validate' %>
    </div>
  </div>
  
  <div class="row">
    <div class="input-field col s12">
      <%= form.label :content %>
    <%= form.text_area :content, class: 'materialize-textarea' %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= form.label :due %>
    <%= form.text_field :due, class: 'datepicker' %>
    </div>
  </div>
  
  <p>
    <label>
      <%= form.check_box :done %>
      <span>Done</span>
    </label>
  </p><br>

  <div class="actions right">
    <%= form.submit class: 'btn waves-effect' %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<div class="container">
    <h3>Editing Todo</h3>

    <%= render 'form', todo: @todo %>

    <%= link_to 'Show', @todo, class: 'btn waves-effect waves-green'%> 
    <%= link_to 'Back', todos_path, class: 'btn waves-effect black'%>

</div>

app/views/todos/index.html.erb
<div class="container">
<p class=" green-text lighten-2" id="notice"><%= notice %></p>

<h3>To_do List</h3>

<table class="table table-divider table-hover table-responsive">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Due</th>
      <th>Done</th>
      <th>user</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <% if todo.user == current_user %>
      <tr>
        <td><%= todo.title %></td>
        <td><%= todo.content %></td>
        <td><%= todo.due %></td>
        <td>
          <% if todo.done == true %>
            done 
          <% else %>
            panding
          <% end %>
        </td>
        <td><%= todo.user.email %></td>
        <td><%= link_to  todo, class: 'waves-effect waves-teal btn-flat' do%> <span class="material-icons"> visibility </span> <% end %></td>
        <td><%= link_to  edit_todo_path(todo), class: 'waves-effect waves-teal btn-flat' do%><span class="material-icons grey-text"> edit </span> <% end %></td>
        <td><%= link_to  todo, method: :delete, data: { confirm: 'Are you sure?' }, class: 'waves-effect waves-teal btn-flat' do%><span class="material-icons red-text"> delete </span> <% end %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br>

<div class="fixed-action-btn">
  <%= link_to new_todo_path, class: 'btn-floating btn-large waves-effect blue accent-2' do %> <i class="large material-icons">add</i> <% end %>
</div>
      
</div>

app/views/todos/new.html.erb
<div class="container">
    <h3>New Todo</h3>

    <%= render 'form', todo: @todo %>

    <%= link_to 'Back', todos_path, class: 'btn waves-effect black'%>

</div><br>

app/views/todos/show.html.erb
<div class="container">
  <p class="green-text lighten-2" id="notice"><%= notice %></p>
  <div class="row">
    <div class="col s12 m12">
      <div class="card white darken-2">
        <div class="card-content black-text">
          <span class="card-title"> <%= @todo.title %></span>
          <p>  <%= @todo.content %></p>
          <p><strong>Due:</strong><%= @todo.due %></p>
          <p>
            <strong>Status:</strong>
            <% if @todo.done == true %>
            done 
          <% else %>
            panding
          <% end %>
          </p>  
        </div>
        <div class="card-action">
          <%= link_to 'Edit', edit_todo_path(@todo), class: 'btn waves-effect btn-primary'%> 
          <%= link_to 'Back', todos_path, class: 'btn waves-effect black'%>
        </div>
      </div>
    </div>
  </div>
</div>